from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.user_login, name='login'),
    path('signup', views.user_signup, name='signup'),
    path('logout', views.user_logout, name='logout'),
    #path('private/<str:room_name>/', views.room, name='room'),
    path('chat/<int:other_user_id>', views.private_chat, name='private_chat'),
    path('edit-profile', views.edit_profile, name='edit_profile'),
    path('update-personal-info', views.update_personal_info, name='update_personal_info'),
    path('profile-page/<int:user_id>', views.profile_page, name='profile_page'),
    path('upload-photo', views.upload_photo, name='upload_photo'),
    path('update-basic-info', views.update_basic_info, name='update_basic_info'),
    path('contacts', views.contacts, name='contacts'),
    path('stories', views.stories, name='stories'),
    path('reset', views.reset, name='reset'),
    path('error-404', views.error_404, name='error-404'),
    path('delete-message/<int:message_id>', views.delete_message, name='delete_message'),
    path('delete-file/<int:message_id>', views.delete_file, name='delete_file'),
    path('users/chat-users', views.chat_users, name='chat_users'),
    path('add-contact/<int:user_id>', views.add_contact, name='add_contact'),
    path('delete-contact/<int:contact_id>', views.delete_contact, name='delete_contact'),
    path('get-contact-profile/<int:contact_id>', views.get_contact_profile, name='get_contact_profile'),
    path('toggle-favorite/<int:contact_id>', views.toggle_favorite, name='toggle_favorite'),
    path('toggle-block/<int:contact_id>', views.toggle_block, name='toggle_block'),
    path('notifications', views.get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/read', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/mark-all-read', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('upload-image', views.upload_image, name='upload_image'),
    path('upload-video', views.upload_video, name='upload_video'),
    path('upload-document', views.upload_document, name='upload_document'),
    path('upload-link', views.upload_link, name='upload_link'),
    path('get-active-time/<int:other_user_id>', views.get_active_time, name='get_active_time'),
    path('get-shared-files/<int:other_user_id>', views.get_shared_files, name='get_shared_files'),
    path('toggle-block-user/<int:user_id>', views.toggle_block_user, name='toggle_block_user'),
    path('archive-chat/<int:other_user_id>', views.archive_chat, name='archive_chat'),
    path('archives', views.archives, name='archives'),
    path('unarchive/<int:other_user_id>', views.unarchive, name='unarchive'),
    path('delete-chat/<int:other_user_id>', views.delete_chat, name='delete_chat'),
    path('search-conversations/', views.search_conversations, name='search_conversations'),
    path('upload-audio', views.upload_audio, name='upload_audio'),
]