# Generated by Django 5.2.1 on 2025-07-12 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Message content')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of the message')),
                ('thread_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the chat thread/room')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver of the message (optional)')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender of the message')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
