# Generated by Django 5.2.5 on 2025-09-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile_birthdate_profile_city_profile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User gender'),
        ),
    ]
