# Generated by Django 5.2.5 on 2025-09-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False, verbose_name='Is the contact blocked?')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when the contact was added')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp when the contact was removed')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_contact_lists', to=settings.AUTH_USER_MODEL, verbose_name='Contact user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Owner of the contact list')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'constraints': [models.UniqueConstraint(fields=('user', 'contact'), name='unique_user_contact')],
            },
        ),
    ]
