# Generated by Django 5.2.5 on 2025-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Is the contact marked as favorite?'),
        ),
    ]
