# Generated by Django 5.2.5 on 2025-09-14 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_contact_is_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Notification message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Has the notification been read?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp of notification creation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User who received the notification')),
            ],
        ),
    ]
