# Generated by Django 5.2.5 on 2025-09-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header_img',
            field=models.ImageField(blank=True, null=True, upload_to='header_images/', verbose_name='Header image'),
        ),
    ]
