# Generated by Django 5.2.5 on 2025-09-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_sharedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shared_images/', verbose_name='Shared image'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Shared link'),
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='shared_videos/', verbose_name='Shared video'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='shared_files/', verbose_name='Shared file'),
        ),
    ]
