# Generated by Django 5.2.5 on 2025-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_sharedfile_image_sharedfile_link_sharedfile_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='thread_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of the chat thread/room'),
        ),
    ]
