# Generated by Django 5.2.5 on 2025-09-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_sharedfile_thread_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='image_caption',
            field=models.TextField(blank=True, null=True, verbose_name='Image caption'),
        ),
    ]
