# Generated by Django 5.2.5 on 2025-09-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_sharedfile_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_notification',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='chat.message', verbose_name='Associated message notification'),
            preserve_default=False,
        ),
    ]
