# Generated by Django 5.2.5 on 2025-09-20 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_notification_message_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default=1, verbose_name='Notification message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='chat.message', verbose_name='Associated message notification'),
        ),
    ]
