# Generated by Django 5.2.5 on 2025-09-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_remove_notification_message_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last seen timestamp'),
        ),
    ]
