# Generated by Django 5.2.5 on 2025-09-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_profile_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Backgroun name')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Background image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
