# Generated by Django 5.2.5 on 2025-10-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_backgroundoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Background name'),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_name', models.CharField(max_length=255, verbose_name='Name of the archived chat thread/room')),
                ('archived_at', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when the chat was archived')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is the archive active?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to=settings.AUTH_USER_MODEL, verbose_name='User who archived the chat')),
            ],
            options={
                'verbose_name': 'Chat Archive',
                'verbose_name_plural': 'Chat Archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
