# Generated by Django 5.2.5 on 2025-10-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_archive_other_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
